const packages = [
  {
    id: 1,
    name: "School bag",
    weight: "2KG",
    origin: "Owerri",
    destination: "Kano",
    priority: "high",
    cost: "NGN 5000",
  },
  {
    id: 2,
    name: "Bag of rice",
    weight: "10KG",
    origin: "Lagos",
    destination: "Abuja",
    priority: "low",
    cost: "NGN 10000",
  },
  {
    id: 3,
    name: "Shoe",
    weight: "1KG",
    origin: "Warri",
    destination: "Kano",
    priority: "medium",
    cost: "NGN 1000",
  },
  {
    id: 4,
    name: "Glass cups",
    weight: "0.5KG",
    origin: "Ibadan",
    destination: "Akure",
    priority: "high",
    cost: "NGN 5000",
  },
  {
    id: 5,
    name: "Glass cups",
    weight: "0.9KG",
    origin: "Uyo",
    destination: "Onitsha",
    priority: "low",
    cost: "NGN 500",
  },
  {
    id: 6,
    name: "Glass cups",
    weight: "05KG",
    origin: "Calaba",
    destination: "Ondo",
    priority: "high",
    cost: "NGN 50000",
  },
  {
    id: 7,
    name: "Glass cups",
    weight: "0.9KG",
    origin: "Uyo",
    destination: "Onitsha",
    priority: "low",
    cost: "NGN 500",
  },
  {
    id: 8,
    name: "Glass cups",
    weight: "05KG",
    origin: "Calaba",
    destination: "Ondo",
    priority: "high",
    cost: "NGN 50000",
  },
  {
    id: 9,
    name: "Glass cups",
    weight: "0.9KG",
    origin: "Uyo",
    destination: "Onitsha",
    priority: "low",
    cost: "NGN 500",
  },
  {
    id: 9,
    name: "Glass cups",
    weight: "05KG",
    origin: "Calaba",
    destination: "Ondo",
    priority: "high",
    cost: "NGN 50000",
  },
  {
    id: 10,
    name: "School bag",
    weight: "2KG",
    origin: "Owerri",
    destination: "Kano",
    priority: "high",
    cost: "NGN 5000",
  },
  {
    id: 11,
    name: "Bag of rice",
    weight: "10KG",
    origin: "Lagos",
    destination: "Abuja",
    priority: "low",
    cost: "NGN 10000",
  },
  {
    id: 12,
    name: "Shoe",
    weight: "1KG",
    origin: "Warri",
    destination: "Kano",
    priority: "medium",
    cost: "NGN 1000",
  },
  {
    id: 13,
    name: "Glass cups",
    weight: "0.5KG",
    origin: "Ibadan",
    destination: "Akure",
    priority: "high",
    cost: "NGN 5000",
  },
  {
    id: 14,
    name: "Glass cups",
    weight: "0.9KG",
    origin: "Uyo",
    destination: "Onitsha",
    priority: "low",
    cost: "NGN 500",
  },
  {
    id: 15,
    name: "Glass cups",
    weight: "05KG",
    origin: "Calaba",
    destination: "Ondo",
    priority: "high",
    cost: "NGN 50000",
  },
  {
    id: 16,
    name: "Glass cups",
    weight: "0.9KG",
    origin: "Uyo",
    destination: "Onitsha",
    priority: "low",
    cost: "NGN 500",
  },
  {
    id: 17,
    name: "Glass cups",
    weight: "05KG",
    origin: "Calaba",
    destination: "Ondo",
    priority: "high",
    cost: "NGN 50000",
  },
  {
    id: 18,
    name: "Glass cups",
    weight: "0.9KG",
    origin: "Uyo",
    destination: "Onitsha",
    priority: "low",
    cost: "NGN 500",
  },
  {
    id: 19,
    name: "Glass cups",
    weight: "05KG",
    origin: "Calaba",
    destination: "Ondo",
    priority: "high",
    cost: "NGN 50000",
  },
  {
    id: 20,
    name: "School bag",
    weight: "2KG",
    origin: "Owerri",
    destination: "Kano",
    priority: "high",
    cost: "NGN 5000",
  },
  {
    id: 21,
    name: "Bag of rice",
    weight: "10KG",
    origin: "Lagos",
    destination: "Abuja",
    priority: "low",
    cost: "NGN 10000",
  },
  {
    id: 22,
    name: "Shoe",
    weight: "1KG",
    origin: "Warri",
    destination: "Kano",
    priority: "medium",
    cost: "NGN 1000",
  },
  {
    id: 23,
    name: "Glass cups",
    weight: "0.5KG",
    origin: "Ibadan",
    destination: "Akure",
    priority: "high",
    cost: "NGN 5000",
  },
  {
    id: 24,
    name: "Glass cups",
    weight: "0.9KG",
    origin: "Uyo",
    destination: "Onitsha",
    priority: "low",
    cost: "NGN 500",
  },
  {
    id: 25,
    name: "Glass cups",
    weight: "05KG",
    origin: "Calaba",
    destination: "Ondo",
    priority: "high",
    cost: "NGN 50000",
  },
  {
    id: 26,
    name: "Glass cups",
    weight: "0.9KG",
    origin: "Uyo",
    destination: "Onitsha",
    priority: "low",
    cost: "NGN 500",
  },
  {
    id: 27,
    name: "Glass cups",
    weight: "05KG",
    origin: "Calaba",
    destination: "Ondo",
    priority: "high",
    cost: "NGN 50000",
  },
  {
    id: 28,
    name: "Glass cups",
    weight: "0.9KG",
    origin: "Uyo",
    destination: "Onitsha",
    priority: "low",
    cost: "NGN 500",
  },
  {
    id: 29,
    name: "Glass cups",
    weight: "05KG",
    origin: "Calaba",
    destination: "Ondo",
    priority: "high",
    cost: "NGN 50000",
  },
];

const getAllPackages = () => packages;

const getSinglePackage = () => {
  const singlePackage = {
    id: 1,
    name: "school bag",
    pickupAddress: "No 5, Ajoke Ajose str, V.I, Lagos",
    deliveryAddress: "No 43, Akintola str, Maitama, Abuja",
    deliveryPeriod: 2,
    cost: 2000,
    weight: 10,
    origin: "Lagos",
    destination: "Abuja",
    info: "A small school bag",
  };
  return singlePackage;
};

export { getAllPackages, getSinglePackage };
