const packages = [
  {
    name: "School bag",
    weight: "2KG",
    origin: "Owerri",
    destination: "Kano",
    priority: "high",
    cost: "NGN 5000",
  },
  {
    name: "Bag of rice",
    weight: "10KG",
    origin: "Lagos",
    destination: "Abuja",
    priority: "low",
    cost: "NGN 10000",
  },
  {
    name: "Shoe",
    weight: "1KG",
    origin: "Warri",
    destination: "Kano",
    priority: "medium",
    cost: "NGN 1000",
  },
  {
    name: "Glass cups",
    weight: "0.5KG",
    origin: "Ibadan",
    destination: "Akure",
    priority: "high",
    cost: "NGN 5000",
  },
  {
    name: "Glass cups",
    weight: "0.9KG",
    origin: "Uyo",
    destination: "Onitsha",
    priority: "low",
    cost: "NGN 500",
  },
  {
    name: "Glass cups",
    weight: "05KG",
    origin: "Calaba",
    destination: "Ondo",
    priority: "high",
    cost: "NGN 50000",
  },
  {
    name: "Glass cups",
    weight: "0.9KG",
    origin: "Uyo",
    destination: "Onitsha",
    priority: "low",
    cost: "NGN 500",
  },
  {
    name: "Glass cups",
    weight: "05KG",
    origin: "Calaba",
    destination: "Ondo",
    priority: "high",
    cost: "NGN 50000",
  },
  {
    name: "Glass cups",
    weight: "0.9KG",
    origin: "Uyo",
    destination: "Onitsha",
    priority: "low",
    cost: "NGN 500",
  },
  {
    name: "Glass cups",
    weight: "05KG",
    origin: "Calaba",
    destination: "Ondo",
    priority: "high",
    cost: "NGN 50000",
  },
  {
    name: "School bag",
    weight: "2KG",
    origin: "Owerri",
    destination: "Kano",
    priority: "high",
    cost: "NGN 5000",
  },
  {
    name: "Bag of rice",
    weight: "10KG",
    origin: "Lagos",
    destination: "Abuja",
    priority: "low",
    cost: "NGN 10000",
  },
  {
    name: "Shoe",
    weight: "1KG",
    origin: "Warri",
    destination: "Kano",
    priority: "medium",
    cost: "NGN 1000",
  },
  {
    name: "Glass cups",
    weight: "0.5KG",
    origin: "Ibadan",
    destination: "Akure",
    priority: "high",
    cost: "NGN 5000",
  },
  {
    name: "Glass cups",
    weight: "0.9KG",
    origin: "Uyo",
    destination: "Onitsha",
    priority: "low",
    cost: "NGN 500",
  },
  {
    name: "Glass cups",
    weight: "05KG",
    origin: "Calaba",
    destination: "Ondo",
    priority: "high",
    cost: "NGN 50000",
  },
  {
    name: "Glass cups",
    weight: "0.9KG",
    origin: "Uyo",
    destination: "Onitsha",
    priority: "low",
    cost: "NGN 500",
  },
  {
    name: "Glass cups",
    weight: "05KG",
    origin: "Calaba",
    destination: "Ondo",
    priority: "high",
    cost: "NGN 50000",
  },
  {
    name: "Glass cups",
    weight: "0.9KG",
    origin: "Uyo",
    destination: "Onitsha",
    priority: "low",
    cost: "NGN 500",
  },
  {
    name: "Glass cups",
    weight: "05KG",
    origin: "Calaba",
    destination: "Ondo",
    priority: "high",
    cost: "NGN 50000",
  },
  {
    name: "School bag",
    weight: "2KG",
    origin: "Owerri",
    destination: "Kano",
    priority: "high",
    cost: "NGN 5000",
  },
  {
    name: "Bag of rice",
    weight: "10KG",
    origin: "Lagos",
    destination: "Abuja",
    priority: "low",
    cost: "NGN 10000",
  },
  {
    name: "Shoe",
    weight: "1KG",
    origin: "Warri",
    destination: "Kano",
    priority: "medium",
    cost: "NGN 1000",
  },
  {
    name: "Glass cups",
    weight: "0.5KG",
    origin: "Ibadan",
    destination: "Akure",
    priority: "high",
    cost: "NGN 5000",
  },
  {
    name: "Glass cups",
    weight: "0.9KG",
    origin: "Uyo",
    destination: "Onitsha",
    priority: "low",
    cost: "NGN 500",
  },
  {
    name: "Glass cups",
    weight: "05KG",
    origin: "Calaba",
    destination: "Ondo",
    priority: "high",
    cost: "NGN 50000",
  },
  {
    name: "Glass cups",
    weight: "0.9KG",
    origin: "Uyo",
    destination: "Onitsha",
    priority: "low",
    cost: "NGN 500",
  },
  {
    name: "Glass cups",
    weight: "05KG",
    origin: "Calaba",
    destination: "Ondo",
    priority: "high",
    cost: "NGN 50000",
  },
  {
    name: "Glass cups",
    weight: "0.9KG",
    origin: "Uyo",
    destination: "Onitsha",
    priority: "low",
    cost: "NGN 500",
  },
  {
    name: "Glass cups",
    weight: "05KG",
    origin: "Calaba",
    destination: "Ondo",
    priority: "high",
    cost: "NGN 50000",
  },
];

const getPackageData = () => packages;

export { getPackageData };
